### PR TITLE
fix dox

### PR DESCRIPTION
**Pull request by tomsrocket**

### CODE REVIEW

**Review by JonesH — CHANGES_REQUESTED** [review]
Shouldn't the removal of logging code be a separate commit?

**Review by webwurst — APPROVED** [review]
For now ok, will butcher later

**Comment by webwurst** [comment]
@JonesH 
> Shouldn't the removal of logging code be a separate commit?

Probably yes, but let's just chaos merge in this state of the project :) Can you approve?

**Comment by JonesH** [comment]
ok for now ;)

**Review by webwurst — APPROVED** [review]

**Review by JonesH — APPROVED** [review]

**Pull request merged**
